// scripts/update-version.ts
import { writeFileSync } from 'fs';
import { resolve, dirname } from 'path';

import pkg from '../package.json' with { type: 'json' };

const version = pkg.version;

const versionFileContent = `// This file is automatically generated by scripts/update-version.ts
// Do not modify this file directly.
export const VERSION = '${version}';
`;

// Create the file in your source directory
writeFileSync(resolve(dirname(''), 'src/version.ts'), versionFileContent, 'utf8');

console.log(`Updated src/version.ts to version: ${version}`);